# Generated by Django 3.0.4 on 2020-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('OGRN', models.IntegerField()),
                ('INN', models.IntegerField(primary_key=True, serialize=False)),
                ('chief', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('target', models.TextField(blank=True, null=True)),
                ('price_project', models.FloatField()),
                ('implementation_period', models.DateField(blank=True, null=True)),
                ('sum_of_self_investments', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('term_use_of_the_loan', models.SmallIntegerField()),
                ('proposed_collateral', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
