# Generated by Django 3.0.4 on 2020-03-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('frpv', '0001_initial'), ('frpv', '0002_auto_20200310_1537'), ('frpv', '0003_auto_20200311_1525'), ('frpv', '0004_entry_topic'), ('frpv', '0005_auto_20200328_1657'), ('frpv', '0006_auto_20200328_1703')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('OGRN', models.IntegerField(verbose_name='ОГРН')),
                ('INN', models.IntegerField(verbose_name='ИНН')),
                ('chief', models.CharField(max_length=100, verbose_name='руководитель')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('target', models.TextField(blank=True, null=True, verbose_name='цель и краткое описание')),
                ('price_project', models.FloatField(verbose_name='стоимость проекта')),
                ('implementation_period', models.CharField(default=0, max_length=100, verbose_name='срок реализации проекта')),
                ('sum_of_self_investments', models.FloatField(verbose_name='сумма собственных вложений')),
                ('loan_amount', models.FloatField(verbose_name='сумма займа')),
                ('term_use_of_the_loan', models.SmallIntegerField(verbose_name='срок пользования займа (месяцев)')),
                ('proposed_collateral', models.CharField(max_length=200, verbose_name='предлагаемое обеспечение')),
                ('id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frpv.Topic')),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('blockname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': "Info's",
            },
        ),
    ]
