# Generated by Django 3.0.4 on 2020-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='INN',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='OGRN',
            field=models.IntegerField(verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='chief',
            field=models.CharField(max_length=100, verbose_name='руководитель'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='implementation_period',
            field=models.DateField(blank=True, null=True, verbose_name='срок реализации проекта'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='loan_amount',
            field=models.FloatField(verbose_name='сумма займа'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='name',
            field=models.CharField(max_length=200, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price_project',
            field=models.FloatField(verbose_name='стоимость проекта'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='proposed_collateral',
            field=models.CharField(max_length=200, verbose_name='предлагаемое обеспечение'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='sum_of_self_investments',
            field=models.FloatField(verbose_name='сумма собственных вложений'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='цель и краткое описание'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='term_use_of_the_loan',
            field=models.SmallIntegerField(verbose_name='срок пользования займа (месяцев)'),
        ),
    ]
