# Generated by Django 3.0.4 on 2020-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0002_auto_20200310_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='INN',
            field=models.IntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='implementation_period',
            field=models.CharField(default=0, max_length=100, verbose_name='срок реализации проекта'),
            preserve_default=False,
        ),
    ]
