# Generated by Django 3.0.4 on 2020-03-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0003_auto_20200330_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='img/'),
        ),
    ]
