# Generated by Django 3.0.4 on 2020-04-01 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('frpv', '0005_auto_20200401_1712'), ('frpv', '0006_auto_20200401_1726'), ('frpv', '0007_auto_20200401_1737'), ('frpv', '0008_bid_date')]

    dependencies = [
        ('frpv', '0004_auto_20200330_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Оставленные заявки'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['group'], 'verbose_name_plural': 'Данные сайта'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы новостей'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='target',
            field=models.TextField(verbose_name='цель и краткое описание'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to='pdf/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/время'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='header',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frpv.Topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='info',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to='pdf/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='info',
            name='blockname',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя блока'),
        ),
        migrations.AlterField(
            model_name='info',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа (см. контекст)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(editable=False, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='entry',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время оставления заявки'),
            preserve_default=False,
        ),
    ]
