# Generated by Django 3.0.4 on 2020-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0004_entry_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
