# Generated by Django 3.0.4 on 2020-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0005_auto_20200401_1712_squashed_0008_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='page',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
