# Generated by Django 3.0.4 on 2020-03-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0005_auto_20200328_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': "Info's"},
        ),
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='blockname',
        ),
        migrations.AddField(
            model_name='info',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
