# Generated by Django 3.0.4 on 2020-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frpv', '0006_info_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='price',
            field=models.CharField(blank=True, help_text='только для реализованных проектов', max_length=20, null=True, verbose_name='Сумма займа (млн. руб)'),
        ),
        migrations.AlterField(
            model_name='info',
            name='page',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страница'),
        ),
    ]
